# robotpkg Makefile for:	devel/gz-utils
# Created:			Anthony Mallet on Wed,  5 Feb 2025
#

DISTNAME=	gz-utils-3.0.0

GZ_COMMENT=	classes and functions for robot applications
CATEGORIES=	devel

include ../../simulation/gz-sim/Makefile.common

DEPEND_ABI.spdlog+=	spdlog>=1.6.0

include ../../devel/spdlog/depend.mk
include ../../mk/robotpkg.mk
