# robotpkg map building software
#

COMMENT=	Map building software

SUBDIR+=	dtm-genom
SUBDIR+=	libdtm
SUBDIR+=	mapkit
SUBDIR+=	octomap
SUBDIR+=	regionMap-genom
SUBDIR+=	regionMap-lib
SUBDIR+=	ros-laser-geometry
SUBDIR+=	segkit
SUBDIR+=	worldmodelgrid3d
SUBDIR+=	zone-genom

include ../mk/robotpkg.subdir.mk
