# robotpkg Makefile for:	optimization/casadi
# Created:			Guilhem Saurel on Wed, 7 Aug 2019
#

include ../../optimization/casadi/Makefile.common

CMAKE_ARGS+=		-DWITH_PYTHON=OFF
CMAKE_ARGS+=		-DWITH_PYTHON3=OFF

include ../../mk/robotpkg.mk
