# robotpkg Makefile for:	devel/ros2-rcutils
# Created:			Anthony Mallet on Wed,  6 Apr 2022
#

ROS2_PKG=	rcutils
ROS2_VERSION=	7.2.0

CATEGORIES=	devel
ROS2_COMMENT=	common C functions and data structures.

include ../../meta-pkgs/ros2-core/Makefile.common

include ../../devel/ament-cmake-ros/depend.mk
include ../../mk/robotpkg.mk
