# robotpkg Makefile for:	devel/ament-cmake-ros
# Created:			Anthony Mallet on Wed,  6 Apr 2022
#

ROS2_PKG=	ament_cmake_ros
ROS2_VERSION=	0.15.1
PKGNAME=	$(subst _,-,${DISTNAME})

CATEGORIES=	devel
ROS2_COMMENT=	specific CMake bits in the ament buildsystem.

ROS2_SUBPKGS=\
  ament_cmake_ros			\
  ament_cmake_ros_core

include ../../meta-pkgs/ros2-core/Makefile.common

include ../../mk/robotpkg.mk
