# robotpkg Makefile for:	path/hpp-manipulation
# Created:			Florent Lamiraux on Sat, 7 Mar 2015
#

HPP_PACKAGE=		hpp-manipulation

CATEGORIES=		path
HPP_COMMENT=		Manipulation problem definition and resolution

# TODO
#include ../../wip/hpp-universal-robot/depend.mk

include ../../meta-pkgs/hpp/Makefile.common

include ../../devel/log4cxx/depend.mk
include ../../path/hpp-wholebody-step/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
