# robotpkg Makefile for:	mapping/segkit
# Created:			Anthony Mallet on Tue, 17 Jun 2008
#

DISTNAME=		segkit-1.0.2
CATEGORIES=		mapping
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
COMMENT=		Library to manipulate laser data
LICENSE=		2-clause-bsd

GNU_CONFIGURE=		yes

include ../../devel/mkdep/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
