# robotpkg simulation tools
#

COMMENT=	Simulation tools

SUBDIR+=	dxsim-gazebo
SUBDIR+=	dxsim-gazebo-classic
SUBDIR+=	gazebo-ros-pkgs
SUBDIR+=	gazebocam-classic-genom3
SUBDIR+=	gazeboft-genom3
SUBDIR+=	gz-physics
SUBDIR+=	gz-sensors
SUBDIR+=	gz-sim
SUBDIR+=	hpp-environments
SUBDIR+=	libdart
SUBDIR+=	libdynamixel
SUBDIR+=	libmrsim
SUBDIR+=	morse
SUBDIR+=	morse-yarp
SUBDIR+=	mrsim-gazebo
SUBDIR+=	mrsim-gazebo-classic
SUBDIR+=	mrsim-genom3
SUBDIR+=	openhrp3
SUBDIR+=	optitrack-gazebo
SUBDIR+=	optitrack-gazebo-classic
SUBDIR+=	py-hpp-environments

include ../mk/robotpkg.subdir.mk
