# robotpkg Makefile for:	path/hpp-core
# Created:			Anthony Mallet on Fri, 13 Jul 2007
#

HPP_PACKAGE=	hpp-core
HPP_COMMENT=	Basic classes for general path planning

CATEGORIES=	path

include ../../meta-pkgs/hpp/Makefile.common

include ../../path/hpp-constraints/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++11.mk
include ../../mk/robotpkg.mk
