# robotpkg Makefile for:	devel/jrl-cmakemodules
# Created:			Guilhem Saurel, Oct 27th 2025
#

ORG=			jrl-umi3218
NAME=			jrl-cmakemodules
VERSION=		1.1.2

CATEGORIES=		devel
COMMENT=		CMake utility toolbox

USE_MASTER_GITHUB=	true

include Makefile.common

DEPEND_ABI.cmake+=	cmake>=3.10

include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
