# robotpkg Makefile for:	mapping/mapkit
# Created:			Anthony Mallet on Tue, 17 Jun 2008
#

DISTNAME=		mapkit-1.0.2
CATEGORIES=		mapping
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		2D, segment-based map building tools
LICENSE=		2-clause-bsd

GNU_CONFIGURE=		yes

include ../../devel/mkdep/depend.mk
include ../../middleware/pocolibs/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../localization/odokit/depend.mk
include ../../mapping/segkit/depend.mk
include ../../mk/sysdep/pkg-config.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
