# robotpkg Makefile for:	localization/odokit
# Created:			Anthony Mallet on Tue, 17 Jun 2008
#

DISTNAME=		odokit-1.0.1
CATEGORIES=		localization
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Library to manipulate odometry data
LICENSE=		2-clause-bsd

GNU_CONFIGURE=		yes

include ../../devel/mkdep/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../mapping/segkit/depend.mk
include ../../mk/sysdep/pkg-config.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
