# robotpkg Makefile for:	devel/gz-plugin
# Created:			Anthony Mallet on Thu,  6 Feb 2025
#

DISTNAME=	gz-plugin-3.0.0

GZ_COMMENT=	plugin loader
CATEGORIES=	devel

include ../../simulation/gz-sim/Makefile.common

DEPEND_ABI.gz-utils+=	gz-utils>=3<4

include ../../devel/gz-utils/depend.mk
include ../../sysutils/gz-tools/depend.mk
include ../../mk/robotpkg.mk
